export const liquors = [
  'Cognac/Brandy',
  'Gin',
  'Mezcal',
  'Rum',
  'Tequila',
  'Whiskey',
  'Vodka',
]

export const ingredients = [
  'Lemon Juice',
  'Lime Juice',
  'Orange Juice',
  'Pineapple Juice',
  'Simple Syrup',
  'Honey Syrup',
  'Ginger Syrup',
  'Cinnamon Syrup',
  'Lemon Twist',
  'Orange Twist',
  'Angostura Bitters',
  'Orange Bitters',
  'Peychaud\'s Bitters',
  'Sweet Vermouth',
  'Dry Vermouth',
  'Ginger Beer',
  'Triple Sec',
  'Club Soda',
  'Tonic Water',
  'Maraschino Liqueur',
  'Averna Amaro',
  'Grenadine',
  'Orgeat',
  'Overproof Jamaican Rum',
  ].sort()